# Generated by Django 5.0.6 on 2024-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_event_participant_list_alter_news_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(default="media/default.png", upload_to="media/"),
        ),
    ]
